# Generated by Django 4.2.3 on 2023-09-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResPasToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentUser', models.CharField(max_length=50, null=True)),
                ('PassToken', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
