# Generated by Django 4.2.3 on 2023-09-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpverify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respastoken',
            name='CurrentUser',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
